/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MyBetsRouteImport } from './routes/my-bets'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ApiPublicHooksRefreshSportsDataRouteImport } from './routes/api/public/hooks/refresh-sports-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsRoute = MyBetsRouteImport.update({
  id: '/my-bets',
  path: '/my-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshSportsDataRoute =
  ApiPublicHooksRefreshSportsDataRouteImport.update({
    id: '/api/public/hooks/refresh-sports-data',
    path: '/api/public/hooks/refresh-sports-data',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historical': typeof HistoricalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-bets': typeof MyBetsRoute
  '/record': typeof RecordRoute
  '/api/public/hooks/refresh-sports-data': typeof ApiPublicHooksRefreshSportsDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historical': typeof HistoricalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-bets': typeof MyBetsRoute
  '/record': typeof RecordRoute
  '/api/public/hooks/refresh-sports-data': typeof ApiPublicHooksRefreshSportsDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/historical': typeof HistoricalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-bets': typeof MyBetsRoute
  '/record': typeof RecordRoute
  '/api/public/hooks/refresh-sports-data': typeof ApiPublicHooksRefreshSportsDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/historical'
    | '/leaderboard'
    | '/my-bets'
    | '/record'
    | '/api/public/hooks/refresh-sports-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/historical'
    | '/leaderboard'
    | '/my-bets'
    | '/record'
    | '/api/public/hooks/refresh-sports-data'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/historical'
    | '/leaderboard'
    | '/my-bets'
    | '/record'
    | '/api/public/hooks/refresh-sports-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoricalRoute: typeof HistoricalRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MyBetsRoute: typeof MyBetsRoute
  RecordRoute: typeof RecordRoute
  ApiPublicHooksRefreshSportsDataRoute: typeof ApiPublicHooksRefreshSportsDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets': {
      id: '/my-bets'
      path: '/my-bets'
      fullPath: '/my-bets'
      preLoaderRoute: typeof MyBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-sports-data': {
      id: '/api/public/hooks/refresh-sports-data'
      path: '/api/public/hooks/refresh-sports-data'
      fullPath: '/api/public/hooks/refresh-sports-data'
      preLoaderRoute: typeof ApiPublicHooksRefreshSportsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoricalRoute: HistoricalRoute,
  LeaderboardRoute: LeaderboardRoute,
  MyBetsRoute: MyBetsRoute,
  RecordRoute: RecordRoute,
  ApiPublicHooksRefreshSportsDataRoute: ApiPublicHooksRefreshSportsDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
